#!/usr/bin/env bash
set -euo pipefail

# OptimusHQ Setup Script
# Checks prerequisites, configures environment, builds images, and starts the platform.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Prerequisites ──────────────────────────────────────────────────────────

info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  error "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
  exit 1
fi
ok "Docker found: $(docker --version)"

if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 is required. Update Docker or install the compose plugin."
  exit 1
fi
ok "Docker Compose found: $(docker compose version --short)"

if ! docker info &>/dev/null 2>&1; then
  error "Docker daemon is not running. Start Docker and try again."
  exit 1
fi
ok "Docker daemon is running"

# Check Claude CLI credentials
if [ ! -f "$HOME/.claude/.credentials.json" ]; then
  warn "Claude credentials not found at ~/.claude/.credentials.json"
  warn "Run 'claude' locally first to authenticate, then re-run this script."
  exit 1
fi
ok "Claude credentials found"

# ── Environment ────────────────────────────────────────────────────────────

ENV_FILE="$SCRIPT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  info "Found existing .env file"
else
  info "Creating .env file..."

  # Docker GID
  DOCKER_GID=$(getent group docker 2>/dev/null | cut -d: -f3 || stat -c '%g' /var/run/docker.sock 2>/dev/null || echo "")
  if [ -z "$DOCKER_GID" ]; then
    warn "Could not detect Docker GID. You may need to set DOCKER_GID manually in .env"
    DOCKER_GID="999"
  fi

  # Git config
  GIT_NAME=$(git config --global user.name 2>/dev/null || echo "")
  GIT_EMAIL=$(git config --global user.email 2>/dev/null || echo "")

  cat > "$ENV_FILE" <<EOF
# OptimusHQ Configuration
# Generated by setup.sh on $(date -Iseconds)

# Login credentials
AUTH_USER=admin
AUTH_PASS=changeme

# Docker group ID (for socket access)
DOCKER_GID=$DOCKER_GID

# Projects directory (absolute path, no ~)
# HOST_PROJECTS_DIR=$HOME/projects

# Git identity for agent commits
GIT_AUTHOR_NAME=${GIT_NAME:-$(whoami)}
GIT_AUTHOR_EMAIL=${GIT_EMAIL:-$(whoami)@localhost}
GIT_COMMITTER_NAME=${GIT_NAME:-$(whoami)}
GIT_COMMITTER_EMAIL=${GIT_EMAIL:-$(whoami)@localhost}

# Agent resource limits (optional)
# AGENT_MEMORY_LIMIT=4294967296
# AGENT_CPU_LIMIT=2
# AGENT_PIDS_LIMIT=512

# Security (optional)
# AGENT_RUNTIME=sysbox-runc
# AGENT_DOCKER_ACCESS=socket
EOF

  ok "Created .env — edit it to change credentials and settings"
fi

# Source .env for this script
set -a
source "$ENV_FILE"
set +a

# ── Projects directory ─────────────────────────────────────────────────────

PROJECTS_DIR="${HOST_PROJECTS_DIR:-$HOME/projects}"
if [ ! -d "$PROJECTS_DIR" ]; then
  info "Creating projects directory: $PROJECTS_DIR"
  mkdir -p "$PROJECTS_DIR"
fi

# Ensure writable by current user (container runs as uid 1000)
if [ ! -w "$PROJECTS_DIR" ]; then
  warn "$PROJECTS_DIR is not writable. Fixing ownership..."
  sudo chown "$(id -u):$(id -g)" "$PROJECTS_DIR"
fi
ok "Projects directory: $PROJECTS_DIR"

# ── Build images ───────────────────────────────────────────────────────────

info "Building platform and base agent image..."
docker compose build

ok "Platform and base agent image built"

# Specialized agent images (optional)
echo ""
read -rp "Build specialized agent images (node, python, browser, flutter)? [y/N] " build_extra
if [[ "$build_extra" =~ ^[Yy] ]]; then
  info "Building specialized agent images..."
  docker compose --profile agent-images build
  ok "Specialized images built"
else
  info "Skipping specialized images (run 'docker compose --profile agent-images build' later)"
fi

# ── Start ──────────────────────────────────────────────────────────────────

echo ""
read -rp "Start OptimusHQ now? [Y/n] " start_now
if [[ ! "$start_now" =~ ^[Nn] ]]; then
  info "Starting OptimusHQ..."
  docker compose up -d
  echo ""
  echo -e "${GREEN}╔═══════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║${NC}  OptimusHQ is running!                            ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}                                                   ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  URL:   ${CYAN}http://localhost:3001${NC}                    ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Login: ${YELLOW}${AUTH_USER:-admin}${NC} / ${YELLOW}${AUTH_PASS:-changeme}${NC}                  ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}                                                   ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Logs:  docker compose logs -f optimushq          ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Stop:  docker compose down                       ${GREEN}║${NC}"
  echo -e "${GREEN}╚═══════════════════════════════════════════════════╝${NC}"
else
  echo ""
  info "Run 'docker compose up -d' when ready to start."
fi
